{% set version = "1.7.2" %}

package:
  name: fastapi-offline
  version: {{ version }}

source:
  - folder: dist
    url: https://pypi.io/packages/source/f/fastapi-offline/fastapi_offline-{{ version }}.tar.gz
    sha256: 1e18ec9fe8c9acb717a4e0a898e681e44412d3d51173681a9a0af6bc3813f927
  - folder: src
    url: https://github.com/turettn/fastapi_offline/archive/refs/tags/v{{ version }}.tar.gz
    sha256: a29b21cbb0e383e0ba4d12f3419708289adca62f050c34e6b0461534cf94da61
  # third-party licenses
  - fn: fastapi-LICENSE-MIT
    url: https://raw.githubusercontent.com/tiangolo/fastapi/master/LICENSE
    sha256: 4ec89ffc81485b97fec584b2d4a961032eeffe834453894fd9c1274906cc744e
  - fn: redoc-LICENSE-MIT
    url: https://raw.githubusercontent.com/Redocly/redoc/master/LICENSE
    sha256: d3026d549cf68ab7355bcfa85877bf8f845b3334a7efbfdc63936432fb34ff0e
  - fn: swagger-ui-LICENSE-APACHE-2.0
    url: https://raw.githubusercontent.com/swagger-api/swagger-ui/master/LICENSE
    sha256: cfc7749b96f63bd31c3c42b5c471bf756814053e847c10f3eb003417bc523d30
  - fn: swagger-ui-NOTICE-APACHE-2.0
    url: https://raw.githubusercontent.com/swagger-api/swagger-ui/master/NOTICE
    sha256: 0d20d1adef18aee3f40dd258172155521ce702ac445cb5f7b7d60ed32dad2fb2

build:
  number: 0
  noarch: python
  script: cd dist && {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - fastapi >=0.99.0
    - pip
    - python >=3.8
  run:
    - fastapi >=0.99.0
    - python >=3.8

test:
  source_files:
    - src/tests
  imports:
    - fastapi_offline
  commands:
    - pip check
    - pytest src/tests -vv --cov fastapi_offline --no-cov-on-fail --cov-report=term-missing:skip-covered --cov-fail-under=97
    - mypy --strict -m fastapi_offline
  requires:
    - mypy
    - pip
    - pytest-cov
    - requests
    - starlette-full

about:
  home: https://github.com/turettn/fastapi_offline
  summary: FastAPI without reliance on CDNs for docs
  license: MIT
  license_file:
    - dist/LICENSE
    - fastapi-LICENSE-MIT
    - redoc-LICENSE-MIT
    - swagger-ui-LICENSE-APACHE-2.0
    - swagger-ui-NOTICE-APACHE-2.0

extra:
  recipe-maintainers:
    - bollwyvl
